### ISSUE TITLE
Can't run the iOS app out of the box

### ISSUE THREAD

**Issue by iadcialim** [M0Coding/Pokedex#6]
I get this when running the app from Android Studio (Flamingo)
<img width="644" alt="ios error" src="https://user-images.githubusercontent.com/14870470/237015558-69b82a0c-4c71-4336-86dc-536f36cb4064.png">

**Comment by JacquesSmuts** [comment]
1) You need to make sure your build environment is correct by using kdoctor.  See here:
https://github.com/JetBrains/compose-multiplatform-ios-android-template#set-up-the-environment|

2) under Xcode project scheme:, select Pokedex instead of Pods-Pokedex.

Not sure why Pods-pokedex is selected by default though 🤷

**Comment by iadcialim** [comment]
> under Xcode project scheme:, select Pokedex instead of Pods-Pokedex.

Thanks @JacquesSmuts. This fixed it for me
